find_trending_companies:
  description: >
    Search for exactly 2-3 trending companies in {sector} from recent news (2024-2025).
    Focus on companies with significant recent developments, earnings releases, or market movements.
    Do not search for the same companies repeatedly. Complete this task efficiently.
  expected_output: >
    A structured list of exactly 2-3 trending companies in {sector} with name, ticker, and specific reason for trending.
  agent: trending_company_finder
  output_file: output/trending_companies.json
  max_iter: 3

research_trending_companies:
  description: >
    For each company from the trending list, conduct focused research and analysis.
    Research each company systematically and provide analysis for ALL companies before concluding.
    Do not get stuck researching the same company repeatedly.
  expected_output: >
    A comprehensive research report containing market position, future outlook, and investment potential for each trending company.
  agent: financial_researcher
  context:
    - find_trending_companies
  output_file: output/research_report.json
  max_iter: 5

pick_best_company:
  description: >
    Analyze the research findings and select the single best company for investment.
    First: Use the push notification tool to send a brief message about your chosen company.
    Then: Provide a detailed explanation of your choice and why other companies were not selected.
    Complete this decisively without excessive deliberation.
  expected_output: >
    1. Push notification sent with chosen company and brief rationale
    2. Detailed report explaining the chosen company and why others were not selected
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
  max_iter: 3